# Generated by Django 5.2.5 on 2025-08-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_team_delete_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
