# Generated by Django 5.2.5 on 2025-08-22 22:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('buyer_phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('buyer_address', models.TextField(verbose_name='Morada de Entrega')),
                ('buyer_city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('buyer_postal_code', models.CharField(max_length=20, verbose_name='Código Postal')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço da Compra')),
                ('notes', models.TextField(blank=True, verbose_name='Notas Adicionais')),
                ('status', models.CharField(choices=[('pending_payment', 'Aguardando Pagamento'), ('payment_confirmed', 'Pagamento Confirmado'), ('preparing_delivery', 'Preparando Entrega'), ('in_transit', 'Em Trânsito'), ('delivered', 'Entregue'), ('completed', 'Concluída'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada')], default='pending_payment', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhado'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método de Pagamento')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID da Transação')),
                ('tracking_code', models.CharField(blank=True, max_length=100, verbose_name='Código de Rastreamento')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='cars.car')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('buyer_phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('buyer_address', models.TextField(verbose_name='Morada')),
                ('buyer_city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('buyer_postal_code', models.CharField(max_length=20, verbose_name='Código Postal')),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Proposto')),
                ('message', models.TextField(help_text='Mensagem para o vendedor', verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceite pelo Vendedor'), ('rejected', 'Rejeitada'), ('negotiating', 'Em Negociação'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller_response', models.TextField(blank=True, verbose_name='Resposta do Vendedor')),
                ('seller_responded_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_purchase_requests', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='cars.car')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_purchase_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Compra',
                'verbose_name_plural': 'Solicitações de Compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('purchase_request', 'Solicitação de Compra'), ('purchase_created', 'Nova Compra'), ('status_changed', 'Status Alterado'), ('payment_confirmed', 'Pagamento Confirmado'), ('delivery_confirmed', 'Entrega Confirmada')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.purchase')),
                ('purchase_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.purchaserequest')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='cars.purchase')),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Histórico de Status',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['buyer', '-created_at'], name='cars_purcha_buyer_i_724e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['seller', '-created_at'], name='cars_purcha_seller__c2c8fa_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['status', '-created_at'], name='cars_purcha_status_c1071b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['payment_status', '-created_at'], name='cars_purcha_payment_3adfe1_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['buyer', '-created_at'], name='cars_purcha_buyer_i_9fec85_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['seller', '-created_at'], name='cars_purcha_seller__652151_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status', '-created_at'], name='cars_purcha_status_6e27dc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='cars_notifi_user_id_bab7ef_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', '-created_at'], name='cars_notifi_type_8bf31a_idx'),
        ),
    ]
