# Generated by Django 5.2.5 on 2025-08-23 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_purchase_purchaserequest_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('file', 'Ficheiro'), ('system', 'Sistema')], default='text', max_length=20, verbose_name='Tipo de Mensagem')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_attachments/', verbose_name='Anexo')),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Anexo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Editado em')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Foi editado')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Foi apagado')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Mensagem de Chat',
                'verbose_name_plural': 'Mensagens de Chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('closed', 'Fechado'), ('archived', 'Arquivado')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Última atividade')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fechado em')),
                ('buyer_last_read', models.DateTimeField(blank=True, null=True, verbose_name='Última leitura do comprador')),
                ('seller_last_read', models.DateTimeField(blank=True, null=True, verbose_name='Última leitura do vendedor')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_chats', to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='cars.car', verbose_name='Carro')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_chats', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_chats', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Sala de Chat',
                'verbose_name_plural': 'Salas de Chat',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ChatNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_message', 'Nova Mensagem'), ('chat_started', 'Chat Iniciado'), ('chat_closed', 'Chat Fechado'), ('chat_reopened', 'Chat Reaberto')], max_length=20, verbose_name='Tipo de Notificação')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('is_read', models.BooleanField(default=False, verbose_name='Foi lida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.chatmessage', verbose_name='Mensagem')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cars.chatroom', verbose_name='Sala de Chat')),
            ],
            options={
                'verbose_name': 'Notificação de Chat',
                'verbose_name_plural': 'Notificações de Chat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cars.chatroom', verbose_name='Sala de Chat'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['buyer', 'status'], name='cars_chatro_buyer_i_eebd21_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['seller', 'status'], name='cars_chatro_seller__be8f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['car', 'status'], name='cars_chatro_car_id_45a95f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['-last_activity'], name='cars_chatro_last_ac_272c21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('car', 'buyer')},
        ),
        migrations.AddIndex(
            model_name='chatnotification',
            index=models.Index(fields=['recipient', 'is_read'], name='cars_chatno_recipie_00b132_idx'),
        ),
        migrations.AddIndex(
            model_name='chatnotification',
            index=models.Index(fields=['-created_at'], name='cars_chatno_created_047d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat_room', 'created_at'], name='cars_chatme_chat_ro_5f5f89_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='cars_chatme_sender__2b5a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['-created_at'], name='cars_chatme_created_3d186b_idx'),
        ),
    ]
