# Generated by Django 5.2.5 on 2025-08-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_chatmessage_chatroom_chatnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='auto_closed',
            field=models.BooleanField(default=False, verbose_name='Fechado automaticamente por inatividade'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='buyer_last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última atividade do comprador'),
        ),
    ]
