# Generated by Django 5.2.5 on 2025-08-24 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_chatroom_auto_closed_chatroom_buyer_last_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['car', 'buyer', 'status'], name='cars_chatro_car_id_2e5736_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('car', 'buyer'), name='unique_active_chat_per_buyer_car'),
        ),
    ]
